const Projects: Project[] = [
  {
    id: "robot-arm",
    title: "Robot Arm",
    description: "A 3D printed robot arm with forward kinematics, inverse kinematics, and computer vision tracking",
    image: require("../assets/images/project-screenshots/robot-arm/main.png").default,
    type: "Robotics",
    buttons: {
      github: "https://github.com/Creampelt/pupper-cv",
      report: require("../assets/downloads/robot-cv.pdf").default,
    },
    hidden: false,
    incomplete: false,
  },
  {
    id: "autonomous-navigation-and-slam",
    title: "F1/10 Navigation & SLAM",
    description: "Autonomous navigation and SLAM implementation on a F1/10 car",
    image: [
      require("../assets/images/project-screenshots/nav-and-slam/automota-group.jpg").default,
      require("../assets/images/project-screenshots/nav-and-slam/slam-results.png").default,
    ],
    type: "Robotics",
    buttons: {
      report: require("../assets/downloads/auton-report.pdf").default,
    },
    hidden: false,
    incomplete: false,
  },
  {
    id: "org-assistant",
    title: "Org Assistant",
    description: "A custom-built event manager that can consolidate attendees, link events and check-ins between " +
      "orgs, restrict attendees based on various criteria, and more",
    image: [
      require("../assets/images/project-screenshots/org-assistant/home-page.png").default,
      require("../assets/images/project-screenshots/org-assistant/event-page.png").default,
    ],
    type: "Web App",
    buttons: {
      web: "https://org-assistant.web.app",
      github: "https://github.com/coleweinman/Org-Assistant",
    },
    logIn: {
      username: "test@example.com",
      password: "12345678",
    },
    hidden: false,
    incomplete: false,
  },
  {
    id: "qpp-website",
    title: "Q++ Website",
    description: "Website for Q++, org for LGBT people in CS at UT Austin",
    image: [
      require("../assets/images/project-screenshots/qpp-website/home.png").default,
      require("../assets/images/project-screenshots/qpp-website/get-involved.png").default,
    ],
    type: "Website",
    buttons: {
      web: "https://texasqpp.com",
      github: "https://github.com/Creampelt/qpp-website",
    },
    hidden: false,
    incomplete: false,
  },
  {
    id: "simple-subs",
    title: "Simple Subs",
    description: "A lunch-ordering system for Lick-Wilmerding High School",
    image: require("../assets/images/project-screenshots/simple-subs.png").default,
    type: "Mobile and Web App",
    buttons: {
      ios: "https://apps.apple.com/us/app/simplesubs/id1464274843",
      android: "https://play.google.com/store/apps/details?id=org.lwhs.simplesubs",
      web: "https://simple-subs-app.web.app",
      github: "https://github.com/SimpleSubs/mobile-app",
    },
    hidden: false,
    incomplete: false,
  },
  {
    id: "simple-subs-console",
    title: "Simple Subs Admin Console",
    description: "A console where cafeteria staff can view existing orders and users and update the menu and profile information",
    image: [],
    type: "Web App",
    buttons: {
      web: "https://simple-subs.web.app",
      github: "https://github.com/SimpleSubs/admin-console",
    },
    hidden: true,
    incomplete: false,
  },
  {
    id: "simple-subs-printer",
    title: "Simple Subs Printer",
    description: "A console where cafeteria staff can view existing orders and users and update the menu and profile information",
    image: [],
    type: "Command-line",
    buttons: {
      github: "https://github.com/SimpleSubs/automatic-printer",
    },
    hidden: true,
    incomplete: false,
  },
  {
    id: "speaker",
    title: "Speaker",
    description: "Bluetooth speaker with pitch and volume reactive LEDs",
    image: require("../assets/images/project-screenshots/speaker/full-shot.jpg").default,
    type: "Tech Arts",
    buttons: {
      github: "https://gist.github.com/Creampelt/1b61be5f5196f39ff682ea6d3a81968d",
    },
    hidden: false,
    incomplete: false,
  },
  {
    id: "archive",
    title: "Other Projects",
    description: "",
    type: "Misc",
    image: [
      require("../assets/images/project-screenshots/missfits-website/home.jpg").default,
      require("../assets/images/project-screenshots/tuner-cli/tuner--help.jpg").default,
    ],
    hidden: false,
    incomplete: false,
  },
  {
    id: "hyphen-hacks-helper",
    title: "Hyphen-Hacks Helper",
    description: "App for annual, student-organized school hackathon to help attendees navigate the event",
    image: require("../assets/images/project-screenshots/hyphen-hacks-helper/announcements.jpg").default,
    type: "Mobile",
    buttons: {
      github: "https://github.com/hyphen-hacks/hyphen-hacks-mobile",
    },
    hidden: true,
    incomplete: false,
  },
  {
    id: "missfits-website",
    title: "Missfits Website",
    description: "Team website for FIRST Robotics Competition Team 6418: The Missfits",
    image: [],
    type: "Website",
    buttons: {
      web: "https://team6418.org",
      github: "https://github.com/Creampelt/missfits-website",
    },
    hidden: true,
    incomplete: false,
  },
  {
    id: "tuner-cli",
    title: "Tuner CLI",
    description: "Command-line interface to calculate the pitch, frequency, and intonation of .wav files",
    image: [],
    type: "Command-line",
    buttons: {
      github: "https://github.com/Creampelt/tuner-cli",
    },
    hidden: true,
    incomplete: false,
  },
  {
    id: "sv-for-pete",
    title: "Silicon Valley for Pete",
    description: "Website for grassroots campaign organization Silicon Valley for Pete",
    image: [],
    type: "Website",
    buttons: {
      github: "https://github.com/Creampelt/pete-website",
    },
    hidden: true,
    incomplete: false,
  },
  {
    id: "lamp",
    title: "Lamp",
    description: "LED lamp inspired by the form of bioluminescent millipedes",
    image: [],
    type: "Tech Arts",
    hidden: true,
    incomplete: false,
  },
  {
    id: "chair",
    title: "Chair",
    description: "Folding, industrial-style chair",
    image: [],
    type: "Tech Arts",
    hidden: true,
    incomplete: false,
  },
];

export default Projects;